import { mkdir, readFile, writeFile, cp } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { site, categories } from '../src/site.mjs';
import { projects } from '../src/projects.mjs';

const root = fileURLToPath(new URL('../', import.meta.url));
const out = path.join(root, 'docs');
const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cat = id => categories.find(c => c.id === id);
const arrow = '<span aria-hidden="true">↗</span>';
const a = (label, href, cls = '') => `<a${cls ? ` class="${cls}"` : ''} href="${esc(href)}">${esc(label)} ${arrow}</a>`;
const nav = prefix => `<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="nav-wrap"><a class="brand" href="${prefix}index.html" aria-label="Sumukh Gadavilli home"><img class="brand-mark" src="${prefix}assets/sentinel.svg" alt="Orbital Sentinel emblem" width="36" height="41"><span>SUMUKH GADAVILLI<span class="brand-sub">PRODUCT · DESIGN · PLAY</span></span></a><nav aria-label="Main navigation"><a href="${prefix}index.html#work">Selected work</a><a href="${prefix}index.html#library">Project library</a><a href="${prefix}index.html#about">About</a>${a('Let’s talk', site.linkedin, 'nav-contact')}</nav></div></header>`;
const footer = prefix => `<footer class="site-footer"><a class="footer-mark" href="${site.url}/" aria-label="Back to home"><img class="brand-mark" src="${prefix}assets/sentinel.svg" alt="Orbital Sentinel emblem" width="30" height="34"></a><p>Sumukh Gadavilli <span> / </span> Thoughtful work. Room to play.</p><div>${a('GitHub', site.github)}${a('LinkedIn', site.linkedin)}</div><a href="#top">Back to top ↑</a></footer>`;
function page(title, description, body, prefix = './', route = '/') {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(description)}"><meta name="theme-color" content="#0b1020"><link rel="canonical" href="${site.url}${route}"><meta property="og:type" content="website"><meta property="og:title" content="${esc(title)}"><meta property="og:description" content="${esc(description)}"><meta property="og:url" content="${site.url}${route}"><meta name="twitter:card" content="summary"><link rel="icon" href="${prefix}assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="${prefix}assets/styles.css"><script src="${prefix}assets/app.js" defer></script></head><body id="top">${nav(prefix)}${body}${footer(prefix)}</body></html>`;
}
function art(p, prefix = './', loading = 'lazy') {
  if (p.image) return `<img src="${prefix}assets/projects/${p.image}" alt="${esc(p.imageAlt)}" loading="${loading}" decoding="async" width="1200" height="750">`;
  return `<div class="journey-art" aria-label="${esc(p.name)} journey"><span class="journey-label">${esc(p.format)}</span><ol>${p.diagram.map((step,i)=>`<li><span>${String(i+1).padStart(2,'0')}</span>${esc(step)}</li>`).join('')}</ol><span class="journey-caption">${esc(p.name)} / Journey overview</span></div>`;
}
function card(p, i) {
  return `<article class="project-card ${p.id}"><a class="card-visual" href="projects/${p.id}/" aria-label="Explore ${esc(p.name)}">${art(p)}<span class="open-icon" aria-hidden="true">↗</span></a><div class="card-body"><div class="card-meta"><span>${esc(cat(p.category).short)}</span><span>${esc(p.status)}</span></div><h3><a href="projects/${p.id}/">${esc(p.name)}</a></h3><p>${esc(p.summary)}</p><div class="card-bottom"><span>${esc(p.format)}</span><a href="projects/${p.id}/">Explore project <span aria-hidden="true">→</span></a></div></div></article>`;
}
await mkdir(path.join(out, 'assets'), { recursive: true });
await cp(path.join(root, 'src/assets'), path.join(out, 'assets'), { recursive: true });
await writeFile(path.join(out, '.nojekyll'), '');
const featured = projects.filter(p => p.featured);
const flagship = featured[0];
const home = `<main id="main">
<section class="hero wrap" aria-labelledby="intro-heading"><div class="hero-copy"><p class="eyebrow"><span class="crosshair" aria-hidden="true">+</span> SUMUKH GADAVILLI / PORTFOLIO</p><h1 id="intro-heading">Serious about<br>the problem.<br><em>Playful about<br class="mobile-break"> the possibilities.</em></h1><p class="hero-description">I bring product thinking and thoughtful interfaces to the human side of AI, everyday services, and ideas worth exploring.</p><div class="hero-actions"><a class="button primary" href="#work">Explore my work <span aria-hidden="true">↘</span></a>${a('About me', '#about', 'text-link')}</div></div><a class="hero-feature" href="projects/ai-workflow-review/"><div class="feature-label"><span>FEATURED CASE STUDY</span><span aria-hidden="true">01 / 06</span></div><div class="hero-screen">${art(flagship, './', 'eager')}</div><div class="feature-caption"><div><span>HEALTHCARE × HUMAN–AI INTERACTION</span><h2>Making AI output<br>reviewable.</h2></div><span class="round-arrow" aria-hidden="true">↗</span></div><p>Evidence within reach. Decisions made clear.</p></a></section>
<div class="discipline-strip"><div class="wrap"><span>Healthcare workflows</span><span aria-hidden="true">+</span><span>Product design</span><span aria-hidden="true">+</span><span>Feature experiments</span><span aria-hidden="true">+</span><span>Tools & play</span></div></div>
<section class="wrap section" id="work" aria-labelledby="work-heading"><div class="section-heading"><div><p class="eyebrow">01 / SELECTED WORK</p><h2 id="work-heading">A few things<br>worth exploring<span class="accent">.</span></h2></div><p>Real design stories, working prototypes,<br> and the questions behind them.</p></div><div class="project-grid">${featured.map(card).join('')}</div></section>
<section class="library-section" id="library" aria-labelledby="library-heading"><div class="wrap section"><div class="section-heading"><div><p class="eyebrow">02 / THE FULL COLLECTION</p><h2 id="library-heading">Choose your<br>next rabbit hole<span class="accent">.</span></h2></div><p>Browse the full collection.<br> Each project tells you where it stands.</p></div><div class="filters" role="group" aria-label="Filter projects by category" hidden><button type="button" data-filter="all" aria-pressed="true">All projects <span>${projects.length}</span></button>${categories.map(c=>`<button type="button" data-filter="${c.id}" aria-pressed="false">${esc(c.short)} <span>${projects.filter(p=>p.category===c.id).length}</span></button>`).join('')}</div><p class="result-count" role="status" aria-live="polite">${projects.length} projects across four areas</p><div class="library-list">${categories.map(c=>`<section class="library-group" data-category="${c.id}" id="${c.id}" aria-labelledby="${c.id}-heading"><div class="category-heading"><h3 id="${c.id}-heading">${esc(c.name)}</h3><p>${esc(c.description)}</p></div>${projects.filter(p=>p.category===c.id).map(p=>`<a class="library-row" href="${p.featured ? `projects/${p.id}/` : esc(p.source)}"><div><h4>${esc(p.name)}</h4><p>${esc(p.summary)}</p></div><span class="project-status ${p.status.includes('Concept')||p.status.includes('concept') ? 'concept' : ''}">${esc(p.status)}</span><span class="library-arrow" aria-hidden="true">↗</span></a>`).join('')}</section>`).join('')}</div><p class="catalog-note">Concepts describe proposed work. Implementations contain source code; that label does not imply production readiness. Case studies keep their evidence and limitations alongside the work.</p></div></section>
<section class="wrap section about-section" id="about" aria-labelledby="about-heading"><div><p class="eyebrow">03 / BEHIND THE WORK</p><h2 id="about-heading">Curiosity is<br>the through line<span class="accent">.</span></h2><p class="about-intro">I’m Sumukh. I’m interested in what makes a product understandable, useful, and worth someone’s time.</p><p>My projects span healthcare workflows, product and service design, AI features, and small tools. I care about the judgment behind the interface: what problem matters, which approach fits, and what evidence would change my mind.</p>${a('Connect on LinkedIn', site.linkedin, 'text-link')}</div><div class="principles"><article><span>01</span><div><h3>Understand the situation.</h3><p>Start with the person, the task, and the friction in their way.</p></div></article><article><span>02</span><div><h3>Make the decision clear.</h3><p>Bring evidence, choices, and consequences into view.</p></div></article><article><span>03</span><div><h3>Leave room to learn.</h3><p>Separate what I know from what the next experiment needs to test.</p></div></article></div></section>
<section class="contact-section"><div class="wrap"><p class="eyebrow">NEXT CONVERSATION</p><h2>Have an interesting<br>problem in mind?</h2>${a('Let’s talk', site.linkedin, 'button primary')}<p>Product, design, healthcare, or a good side quest.</p></div></section></main>`;
await writeFile(path.join(out, 'index.html'), page('Sumukh Gadavilli — Product, Design & Play', site.description, home));
for (const [i, p] of featured.entries()) {
  const prefix = '../../';
  const next = featured[(i+1)%featured.length];
  const body = `<main id="main"><section class="wrap case-hero"><a class="back-link" href="../../index.html#work">← Selected work</a><p class="eyebrow">${esc(cat(p.category).name)} / ${esc(p.status)}</p><h1>${esc(p.headline)}</h1><p class="case-intro">${esc(p.intro)}</p><dl class="case-meta"><div><dt>Project</dt><dd>${esc(p.name)}</dd></div><div><dt>Focus</dt><dd>${esc(p.role)}</dd></div><div><dt>Artifacts</dt><dd>${esc(p.format)}</dd></div></dl><div class="case-cover ${p.id}">${art(p, prefix, 'eager')}</div></section><div class="wrap case-layout"><aside class="case-sidebar"><h2>Inside the project</h2><nav aria-label="Case study sections">${p.sections.map((s,i)=>`<a href="#section-${i+1}">${esc(s.title)}</a>`).join('')}<a href="#artifacts">Artifacts & evidence</a></nav></aside><div class="case-content">${p.sections.map((s,i)=>`<section id="section-${i+1}"><h2>${esc(s.title)}</h2><p>${esc(s.text)}</p>${s.image?`<figure><a href="${prefix}assets/projects/${s.image}" aria-label="Open full-size image: ${esc(s.alt)}"><img src="${prefix}assets/projects/${s.image}" alt="${esc(s.alt)}" loading="lazy" width="1200" height="750"></a><figcaption>${esc(s.caption)}</figcaption></figure>`:''}</section>`).join('')}<section id="artifacts" class="evidence-block"><p class="eyebrow">ARTIFACTS & EVIDENCE</p><h2>Explore the work.</h2><p>${esc(p.evidence)}</p><div class="artifact-links">${p.links.map(([label,url])=>a(label,url,'button secondary')).join('')}</div><p class="access-note">Figma files may require sign-in or permission. Public documentation remains available ${a('on GitHub',p.source)}.</p></section></div></div><section class="wrap next-project"><p class="eyebrow">UP NEXT</p><a href="../${next.id}/"><h2>${esc(next.name)}</h2><span aria-hidden="true">→</span></a></section></main>`;
  await mkdir(path.join(out, 'projects', p.id), { recursive: true });
  await writeFile(path.join(out, 'projects', p.id, 'index.html'), page(`${p.name} — Sumukh Gadavilli`, p.summary, body, prefix, `/projects/${p.id}/`));
}
await writeFile(path.join(out, '404.html'), page('Page not found — Sumukh Gadavilli', 'Find your way back to the portfolio.', `<main id="main" class="wrap section not-found"><p class="eyebrow">404 / WRONG TURN</p><h1>This side quest<br>ends here.</h1><p>The page may have moved. The project library has every current entry.</p><a class="button primary" href="${site.url}/#library">Back to the projects →</a></main>`, '/', '/404.html'));
await writeFile(path.join(out,'robots.txt'), `User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
await writeFile(path.join(out,'sitemap.xml'), `<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${['/',...featured.map(p=>`/projects/${p.id}/`)].map(route=>`<url><loc>${site.url}${route}</loc></url>`).join('')}</urlset>`);
const index = `# Project index\n\n[Open the visual portfolio](${site.url}/) · [GitHub profile](${site.github})\n\n${categories.map(c=>`## ${c.name}\n\n${c.description}\n\n| Project | Focus | Status |\n| --- | --- | --- |\n${projects.filter(p=>p.category===c.id).map(p=>`| [${p.name}](${p.featured?`${site.url}/projects/${p.id}/`:p.source}) | ${p.summary} | ${p.status} |`).join('\n')}\n`).join('\n')}\n## Status guide\n\nConcepts describe proposed work. Implementations contain source code, not a guarantee of production readiness. Case studies document decisions and available evidence. Archived projects remain references and are not maintained.\n`;
await writeFile(path.join(root,'PROJECTS.md'), index);
console.log(`Built home, ${featured.length} project pages, 404, sitemap, and project index (${projects.length} projects).`);
