const gh = 'https://github.com/Eskstrom/';
const design = gh + 'figma-portfolio-checkpoint/tree/main/projects/';
export const projects = [
  {
    id: 'ai-workflow-review', name: 'AI Workflow Review', headline: 'Helping people trust what happens next.', category: 'healthcare-operations', status: 'Design case study', featured: true,
    summary: 'Source evidence, clear confirmation, and recovery paths for people reviewing healthcare automation.',
    image: 'healthcare/03-preview.png', imageAlt: 'Healthcare extraction review with editable fields beside a synthetic source document',
    repository: 'figma-portfolio-checkpoint', source: design + 'ai-workflow-review',
    role: 'Sole designer', format: '3 design stories · 10 screens',
    links: [['Complete case study', gh + 'figma-portfolio-checkpoint/blob/main/projects/ai-workflow-review/CASE-STUDY.md'], ['Ten-screen gallery', gh + 'figma-portfolio-checkpoint/blob/main/projects/ai-workflow-review/SCREENS.md'], ['Open Figma', 'https://www.figma.com/design/w5MWfIM7Y9mNZwHV0AfDWg?node-id=6-2']],
    intro: 'A healthcare review experience designed around three questions: where did this answer come from, what am I confirming, and what happens when the system cannot provide an answer?',
    sections: [
      { title: 'The work behind the interface', text: 'I was the sole designer, working through focused testing, shadowing, and feedback from hospital technology and operations partners. My scope was the review experience within a larger set of healthcare workflows. Earlier BPO experience helped me recognize the cost of backtracking and unclear handoffs.' },
      { title: '01 / Keep the evidence within reach', text: 'Reviewers repeatedly searched original documents to verify extracted values. I brought editable information and source material into one workspace, with references, highlighting, and refocus controls. Qualitative feedback indicated less searching and fewer interruptions.', image: 'healthcare/03-preview.png', alt: 'Source document and editable extracted information in the same review workspace', caption: 'Public reconstruction with synthetic records and document illustrations.' },
      { title: '02 / Separate review completion from approval', text: 'An accurate “Not Qualified” result could still make reviewers hesitate over “Everything looks right.” I separated completing the review from approving the referral, using task-specific confirmation language such as “Confirm assessment.” A negative assessment can be correct and ready for handoff.', image: 'healthcare/09-preview.png', alt: 'Qualification criteria and a Not Qualified result with the earlier confirmation wording', caption: 'This captured state preserves the earlier wording that exposed the ambiguity; it does not show the later confirmation-language refinement.' },
      { title: '03 / Preserve an unanswered question', text: 'An unsuccessful insurance lookup is different from a completed check with a negative result. I separated verification status from coverage outcome and worked through correction, retry, and manual verification with its source and time. The next person should understand what was actually checked.', image: 'healthcare/07-preview.png', alt: 'Eligibility review workspace displaying a verified example', caption: 'The gallery shows a verified state for context. The failure and manual-recovery states discussed here are not pictured.' },
      { title: 'What I took forward', text: 'The effort of checking an answer is part of the AI experience. Reviewers need accessible evidence, an explicit decision to own, and a clear next step. Outcomes are qualitative; the numbers inside the reconstructed screens are illustrative.' }
    ],
    evidence: 'Original design experience with qualitative outcomes. The public screens are static reconstructions using synthetic information, not production application code or measured performance results.'
  },
  {
    id: 'moment-comments', name: 'Moment Comments', headline: 'The right conversation. At the right moment.', category: 'new-features', status: 'Feature concept', featured: true,
    summary: 'A timed comment bubble connects short-video reactions to the moment that sparked them.', image: 'moment-comments/concept.svg', imageAlt: 'Four Moment Comments concept screens for playback, discussion, timestamp confirmation, and creator insights',
    repository: 'moment-comments', source: gh + 'moment-comments', role: 'Product concept & interaction design', format: '4 concept states',
    links: [['Concept and product rules', gh + 'moment-comments'], ['Open Figma', 'https://www.figma.com/design/qMnajfGENfkplGhmD8pVNC/?node-id=1-2']],
    intro: 'After a punchline or surprising claim, people often open the comments to see whether others noticed the same thing. This concept keeps that social context connected to the moment itself.',
    sections: [
      { title: 'Start with the moment', text: 'One concise comment bubble appears at a relevant point in playback. Opening it reveals a moment-specific thread, with options to replay the beat, join the discussion, or return to the full feed.' },
      { title: 'Make the association correctable', text: 'A commenter can explicitly choose a timestamp or confirm a suggested one. Inferred associations would compare comment meaning with transcript and scene context. Likes can help rank comments, but are not proof that a timestamp is correct.' },
      { title: 'Keep the viewer in control', text: 'The proposed behavior uses one bubble at a time, a confidence threshold, frequency limits, spoiler prevention, and a hide-reactions control. A viewer correction is stronger evidence than an ambiguous pause or scroll.' },
      { title: 'The next test', text: 'Test whether viewers understand the association, find the comments useful, and can correct timestamps easily. Measure thread opens alongside video completion, dismissals, and correction rates before claiming an improvement.' }
    ], evidence: 'A four-state visual concept and exported SVG board. No connected prototype, trained model, live video integration, or measured user outcome yet.'
  },
  {
    id: 'watch-and-unlock', name: 'Watch & Unlock', headline: 'An optional exchange, made explicit.', category: 'new-features', status: 'Wireframe prototype', featured: true,
    summary: 'Optional sponsor engagement earns tokens for clearly scoped streaming benefits.', image: 'watch-and-unlock/tv-01.svg', imageAlt: 'Watch and Unlock episode-completion offer wireframe showing optional reward choices',
    repository: 'figma-portfolio-checkpoint', source: design + 'watch-and-unlock', role: 'Product concept & wireframes', format: '28 screens · TV + mobile',
    links: [['Case study and wireframes', design + 'watch-and-unlock'], ['Prototype files', design + 'watch-and-unlock/prototype'], ['Verification notes', gh + 'figma-portfolio-checkpoint/blob/main/projects/watch-and-unlock/VERIFICATION.md']],
    intro: 'What would make a viewer’s exchange with advertising understandable and optional? This concept connects episode completion, sponsor engagement, and a precisely described reward.',
    sections: [
      { title: 'Explain the exchange before the action', text: 'The example journey moves from 5 tokens for episode completion to 20 after an ad, 25 after an optional sponsor demo, then 0 after redeeming one eligible ad-break skip. The viewer can continue watching without taking the offer.' },
      { title: 'Design for the exceptions too', text: 'The saved set includes TV, mobile, wallet, playback, and recovery states. A QR scan alone does not earn the bonus. Redemption names the specific episode and ad break instead of implying an entire ad-free episode.' },
      { title: 'What has been checked', text: 'The existing verification notes cover the core balance transitions and selected recovery paths in an offline click-through prototype. Keyboard Tab, Enter or Space, and Escape are supported; directional TV remote behavior is still a design annotation.' },
      { title: 'What needs evidence', text: 'Viewer motivation, reward comprehension, advertiser economics, and the token values need validation. Native Figma components, connected Figma flows, and full remote navigation remain unfinished.' }
    ], evidence: 'Concept and simulated prototype. No real reward accounts, transactions, advertiser partnership, cross-device synchronization, or measured commercial outcome.'
  },
  {
    id: 'cmu-court-reservations', name: 'CMU Court Reservations', headline: 'From finding a court to making it yours.', category: 'product-service-design', status: 'Design in progress', featured: true,
    summary: 'A mobile reservation journey and smartwatch companion for booking and managing a court.', repository: 'figma-portfolio-checkpoint', source: design + 'cmu-court-reservations', role: 'Product & interaction design', format: 'Mobile + smartwatch', diagram: ['Find a court', 'Choose a time', 'Review', 'Manage booking'],
    links: [['Mobile design', 'https://www.figma.com/design/W1i2PizUUUvCtPx4EnxpFx/Sumukh-s-Space?node-id=4606-149'], ['Watch prototype', 'https://www.figma.com/make/RGAbRr2RprARTQoGvNihJw/Smartwatch-App-Prototype']],
    intro: 'A reservation should leave someone certain about what they booked and able to change it. This project brings discovery, selection, confirmation, and cancellation into one coherent journey.',
    sections: [
      { title: 'One journey across two devices', text: 'Seven mobile frames separate finding a court, choosing a time, reviewing the booking, confirmation, management, and cancellation. A smartwatch companion explores the same core task in a smaller interaction space.' },
      { title: 'A deliberate cancellation', text: 'The documented smartwatch check follows booking through management, deliberate cancellation, and a cleared booking count. On mobile, the cancellation-result frame still needs its remaining confirmation copy and actions corrected.' },
      { title: 'What comes next', text: 'Finish mobile frame review and prototype connections; verify duplicate handling, recovery, sharing, and calendar export on the watch. The fixed sample date and ambiguous court label also need correction before a final presentation.' }
    ], evidence: 'Original design with ongoing refinement. Booking data are illustrative, and neither prototype connects to live CMU reservations. Research details and measured outcomes are not supplied in the public artifacts.'
  },
  {
    id: 'fastmail-kiosk', name: 'FastMail Kiosk', headline: 'Make the next step obvious.', category: 'product-service-design', status: 'Interactive concept', featured: true,
    summary: 'A guided shipping flow with clear costs, editable review, and payment recovery.', repository: 'figma-portfolio-checkpoint', source: design + 'fastmail-kiosk', role: 'UX & interaction design', format: '10-step kiosk journey', diagram: ['Address', 'Package details', 'Review cost', 'Confirm'],
    links: [['Open kiosk prototype', 'https://www.figma.com/make/gc3I9jqgY0XMzbZ0SOaPKp/Fast-mail-Kiosk'], ['Project notes', design + 'fastmail-kiosk']],
    intro: 'Shipping a parcel involves unfamiliar choices, physical measurements, and a payment. The kiosk concept turns that sequence into a guided flow with opportunities to review and recover.',
    sections: [
      { title: 'Make costs understandable', text: 'Address, dimensions, weight, handling, pickup, and speed choices lead to an itemized estimate. People can edit the review without losing unrelated selections.' },
      { title: 'Treat recovery as part of the task', text: 'Existing version-5 checks cover required fields, a price change from $19.99 to $29.99 when speed changes, payment decline and retry, and a start-over confirmation that preserves the order if dismissed. These are synthetic demo prices and interaction checks.' },
      { title: 'Be precise about the handoff', text: 'The receipt describes a concept handoff without promising email, postage, or live tracking. Keyboard, narrow-screen, and physical-kiosk accessibility checks remain to be completed.' }
    ], evidence: 'Interactive Figma Make concept with documented functional checks. Payments and shipping are simulated. The checks are not a usability study or accessibility certification.'
  },
  {
    id: 'con-alma', name: 'Con Alma Partnerships', headline: 'Design the service around the visit.', category: 'product-service-design', status: 'Service design study', featured: true,
    summary: 'A service blueprint connects university outreach, redemption, return visits, and feedback.', repository: 'figma-portfolio-checkpoint', source: design + 'con-alma', role: 'Service design', format: 'Blueprint + ecosystem maps', diagram: ['Outreach', 'Visit & redeem', 'Return', 'Feedback'],
    links: [['Service blueprint', 'https://www.figma.com/board/7XDNtOq84HYRb0v3eGOMAi/University-Partnership-Outreach---Engagement-Workflow'], ['Ecosystem map A', 'https://www.figma.com/board/G9y3K23jmz0EpD43RXctbp/Service-Ecosystem-Change-and-Value-Flow'], ['Ecosystem map B', 'https://www.figma.com/board/LMRIR8W3eCJumZlTxOMsNK/Service-Ecosystem-Change-and-Value-Flow']],
    intro: 'A university partnership extends beyond a promotion. This service-design work traces the people, handoffs, and backstage support that connect the first invitation to a repeat visit.',
    sections: [
      { title: 'Connect frontstage and backstage', text: 'The blueprint covers outreach, coupons, point-of-sale validation, social amplification, repeat visits, and feedback. Ecosystem maps examine how value moves between participants across that journey.' },
      { title: 'Preserve the alternatives', text: 'Two ecosystem-map versions remain available alongside the blueprint. They are working artifacts for comparing approaches rather than evidence of a launched partnership.' },
      { title: 'Next refinement', text: 'Consolidate the narrative, align blueprint lanes, clarify labels, and distinguish proposed actions from observed findings. Bibliographic references need verification before citation.' }
    ], evidence: 'Original service-design artifacts. The public checkpoint records review, not a completed service launch or measured change in visits or revenue.'
  },
  { id: 'agency-lending-operations-case-study', name: 'Agency Lending Operations', category: 'healthcare-operations', status: 'Case study + synthetic demo', repository: 'agency-lending-operations-case-study', summary: 'An exception-control center with ownership, SQL checks, and evidence-backed closure.', source: gh + 'agency-lending-operations-case-study' },
  { id: 'seasonal-campaign-launch-readiness', name: 'Campaign Launch Readiness', category: 'healthcare-operations', status: 'Illustrative case study', repository: 'seasonal-campaign-launch-readiness', summary: 'Cross-functional launch gates, accountable owners, and clear go/no-go evidence.', source: gh + 'seasonal-campaign-launch-readiness' },
  { id: 'ai-deployment-command-center', name: 'AI Deployment Command Center', category: 'healthcare-operations', status: 'Concept + scope plan', repository: 'ai-deployment-command-center', summary: 'Separate technical readiness from training, adoption, and unresolved launch blockers.', source: gh + 'ai-deployment-command-center' },
  { id: 'clinical-feedback-insight-hub', name: 'Clinical Feedback Insight Hub', category: 'healthcare-operations', status: 'Concept brief', repository: 'clinical-feedback-insight-hub', summary: 'Distinguish defects, training gaps, and workflow mismatches in implementation feedback.', source: gh + 'clinical-feedback-insight-hub' },
  { id: 'referral-loop-simulator', name: 'Referral Loop Simulator', category: 'healthcare-operations', status: 'Concept brief', repository: 'referral-loop-simulator', summary: 'Explore bottlenecks across outreach, referral, appointment, and follow-up.', source: gh + 'referral-loop-simulator' },
  { id: 'eligibility-reconciliation-workbench', name: 'Eligibility Reconciliation Workbench', category: 'healthcare-operations', status: 'Concept brief', repository: 'eligibility-reconciliation-workbench', summary: 'Explain record matches and preserve manual review for uncertain cases.', source: gh + 'eligibility-reconciliation-workbench' },
  { id: 'workflow-exception-navigator', name: 'Workflow Exception Navigator', category: 'healthcare-operations', status: 'Concept brief', repository: 'workflow-exception-navigator', summary: 'Route operational exceptions with transparent urgency, reasons, and ownership.', source: gh + 'workflow-exception-navigator' },
  { id: 'ai-data-quality-sentinel', name: 'AI Data Quality Sentinel', category: 'healthcare-operations', status: 'Concept brief', repository: 'ai-data-quality-sentinel', summary: 'Connect data-quality alerts to reproducible checks and the people who can act.', source: gh + 'ai-data-quality-sentinel' },
  { id: 'enterprise-llm-model-hub', name: 'Enterprise LLM Model Hub', category: 'product-service-design', status: 'Product case study', repository: 'enterprise-llm-model-hub', summary: 'Select models for workload quality, latency, cost, and governance requirements.', source: gh + 'enterprise-llm-model-hub' },
  { id: 'candidate-search-eval-lab', name: 'Candidate Search Evaluation Lab', category: 'product-service-design', status: 'Concept + measurement plan', repository: 'candidate-search-eval-lab', summary: 'Compare semantic and keyword retrieval against labeled synthetic examples.', source: gh + 'candidate-search-eval-lab' },
  { id: 'marketplace-discovery-diagnostic', name: 'Marketplace Discovery Diagnostic', category: 'product-service-design', status: 'Concept brief', repository: 'marketplace-discovery-diagnostic', summary: 'Find how categories, missing attributes, and filters hide relevant products.', source: gh + 'marketplace-discovery-diagnostic' },
  { id: 'return-risk-explainer', name: 'Return-Risk Explainer', category: 'product-service-design', status: 'Concept brief', repository: 'return-risk-explainer', summary: 'Explain ambiguous product information without claiming proven return reduction.', source: gh + 'return-risk-explainer' },
  { id: 'human-approval-workspace', name: 'Human Approval Workspace', category: 'product-service-design', status: 'Concept brief', repository: 'human-approval-workspace', summary: 'Help reviewers inspect evidence before accepting an automated recommendation.', source: gh + 'human-approval-workspace' },
  { id: 'netflix-shuffle', name: 'Shuffle for Comfort Watching', category: 'new-features', status: 'Feature concept', repository: 'figma-portfolio-checkpoint', summary: 'Choose a familiar episode from previously watched series, with less browsing.', source: design + 'netflix-shuffle' },
  { id: 'focusflow', name: 'FocusFlow', category: 'tools-play', status: 'Implementation', repository: 'focusflow', summary: 'A terminal focus timer with task tracking, local storage, and session analytics.', source: gh + 'focusflow' },
  { id: '2048game', name: '2048 Game', category: 'tools-play', status: 'Implementation', repository: '2048game', summary: 'A browser puzzle exploring feedback, touch controls, undo, and saved preferences.', source: gh + '2048game' },
  { id: 'focusflow-ai-planner', name: 'FocusFlow AI Planner', category: 'tools-play', status: 'Concept brief', repository: 'focusflow-ai-planner', summary: 'A weekly planning concept that respects availability and user overrides.', source: gh + 'focusflow-ai-planner' },
  { id: 'case-study-evidence-studio', name: 'Case Study Evidence Studio', category: 'tools-play', status: 'Concept brief', repository: 'case-study-evidence-studio', summary: 'Keep facts, assumptions, evidence, and unverified claims distinguishable.', source: gh + 'case-study-evidence-studio' },
  { id: 'claritydesk-rag', name: 'ClarityDesk RAG', category: 'tools-play', status: 'Concept brief', repository: 'claritydesk-rag', summary: 'Source-grounded support answers with clarification and escalation paths.', source: gh + 'claritydesk-rag' },
  { id: 'research-orchestra', name: 'Research Orchestra', category: 'tools-play', status: 'Concept brief', repository: 'research-orchestra', summary: 'A proposed multi-agent workflow for briefs with traceable sources.', source: gh + 'research-orchestra' },
  { id: 'agent-use-case-prioritizer', name: 'Agent Use-Case Prioritizer', category: 'tools-play', status: 'Concept brief', repository: 'agent-use-case-prioritizer', summary: 'A transparent rubric for choosing automation, assistance, or no intervention.', source: gh + 'agent-use-case-prioritizer' },
  { id: 'governance-guardrails-toolkit', name: 'Governance Guardrails Toolkit', category: 'tools-play', status: 'Concept brief', repository: 'governance-guardrails-toolkit', summary: 'Connect AI launch risks to specific controls and evidence requirements.', source: gh + 'governance-guardrails-toolkit' },
  { id: 'opening-explainer', name: 'Opening Explainer', category: 'tools-play', status: 'Archived implementation', repository: 'opening-explainer', summary: 'A chess-learning reference with move-by-move explanations. Retained as archived work.', source: gh + 'opening-explainer' }
];
